# 파이토치 기본 사용법

pytorch의 기본 사용법을 tensor datatype부터 mnist 훈련까지 설명

## part 1: 필요한 패키지 임포트

현재 프로젝트에서 필요한 패키지를 임포트해준다.

In [2]:
import numpy as np
import scipy
import sklearn
import matplotlib.pyplot as plt
import pandas as pd
import PIL
import time

In [3]:
import torch
import torch.nn as nn
from torch.autograd import Variable
import torchvision.datasets as dset
import torchvision.transforms as transforms
import torch.nn.functional as F
import torch.optim as optim

## part 2: 파이토치 데이터타입

### torch.Tensor
파이토치의 기본 Array 자료형은 torch.Tensor이다.

Tensor는 numpy의 array와 비슷하지만 GPU연산을 지원한다. Tensor의 데이터타입을 확인하고 싶으면 type(TensorData)를, Tensor의 shape을 확인하고 싶으면 TensorData.size()를 이용하면 된다.

* 직접 Tensor 생성, torch.tensor()
* 각 요소가 모두 0인 Tensor 생성, torch.zeros()
* 각 요소가 모두 1인 Tensor 생성, torch.ones()
* uniform distributed random Tensor 생성, torch.rand()
* normal distributed random Tensor 생성, torch.randn()

In [5]:
x = torch.zeros(5, 3)
print(x)
print(type(x))
y = torch.tensor([[1, 2],[3, 4]])
print(y)
print(y.size())

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
<class 'torch.Tensor'>
tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])


In [6]:
print("---------")
zero_tensor = torch.zeros(2, 2)
print(zero_tensor)
one_tensor = torch.ones(2, 2)
print(one_tensor)
random_tensor = torch.rand(2, 2)
print(random_tensor)
normal_tensor = torch.randn(2, 2)
print(normal_tensor)

---------
tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.6084, 0.6943],
        [0.1454, 0.8221]])
tensor([[-1.2354, -0.3589],
        [-0.8280, -0.4124]])


### dtype

각 원소의 데이터 타입 또한 정의할 수 있다. 파이토치는 아래와 같은 데이터 타입들을 가지고 있다.

* 64 bit floating point: torch.float64
* 32 bit floating point: torch.float32
* 16 bit floating point: torch.float16
* 8 bit unsigned int: torch.uint8
* 8 bit int: torch.int8
* 16 bit int: torch.int16
* 32 bit int: torch.int32
* 64 bit int: torch.int64
* boolean: torch.bool

In [4]:
x_real = torch.tensor([3, 4, 5, 6], dtype=torch.float32)
y_real = torch.tensor([7, 8, 9, 10], dtype=torch.float32)
x_int = torch.tensor([3, 4, 5, 6], dtype=torch.int32)
y_int = torch.tensor([7, 8, 9, 10], dtype=torch.int32)

print(x_real / y_real)
print(x_int / y_int)

tensor([0.4286, 0.5000, 0.5556, 0.6000])
tensor([0, 0, 0, 0], dtype=torch.int32)


## part 3. 사칙연산

사칙연산은 넘파이와 동일하게 +, -, *, /연산자로 할 수 있다.

In [31]:
x1 = torch.tensor([[1.0, 2.0],[3.0, 4.0]])
x2 = torch.tensor([[2.0, 3.0],[4.0, 5.0]])
print(x1 + x2)
print(x1 - x2)
print(x1 * x2)
print(x1 / x2)

tensor([[3., 5.],
        [7., 9.]])
tensor([[-1., -1.],
        [-1., -1.]])
tensor([[ 2.,  6.],
        [12., 20.]])
tensor([[0.5000, 0.6667],
        [0.7500, 0.8000]])


* Tensor.view(): Array reshape

In [30]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x)
print(x.size())
y = x.view(1, -1)
print(y)
print(y.size())

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
tensor([[1, 2, 3, 4, 5, 6]])
torch.Size([1, 6])


Indexing and slicing

In [12]:
x = torch.rand(50, 50)
print(x.size())

y = x[0:10, 20:40]
print(y.size())

z = x[x > 0.5]
print(z)
print(z.size())

torch.Size([50, 50])
torch.Size([10, 20])
tensor([0.6073, 0.6094, 0.5311,  ..., 0.5972, 0.6418, 0.6579])
torch.Size([1267])


In [7]:
a = torch.randn(2, 2)
b = a.numpy()
print(type(a))
print(type(b))
a.div_(3)
print(a)
print(b)

c = np.array([[2., 4.],[6., 8.]])
d = torch.from_numpy(c)
print(type(c))
print(type(d))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>
tensor([[ 0.2323, -0.2769],
        [-0.2474,  0.4452]])
[[ 0.23233348 -0.27687767]
 [-0.24738401  0.44523707]]
<class 'numpy.ndarray'>
<class 'torch.Tensor'>


In [32]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

y = x + 2
print(y)

print(y.grad_fn)

z = y*y*3
out = z.mean()
print(z, out)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
True
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [31]:
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


# pytorch로 CNN을 이용하여 MNIST 훈련

Nvidia GPU를 이용하여 CNN 네트워크를 훈련시켜 99% 이상 정확도 달성

## step 1. 데이터 불러오기

torchvision.datasets 모듈에서 편리하게 mnist 데이터를 가져올 수 있다. 

In [3]:
# step 1. torchvision 모듈의 datasets 기능을 이용하여 MNIST 데이터셋을 불러온다.
import torchvision.datasets as datasets

# 이미지를 불러올 때 Tensor형태로(원형 = PIL image), mean = 0.5, std = 1.0으로 정규화하여 저장
trans = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5,), (1.0,))])

# MNIST 데이터셋 불러오기
mnist_trainset = datasets.MNIST(root='./data', train=True, download=True, transform=trans)
mnist_testset = datasets.MNIST(root='./data', train=False, download=True, transform=trans)

# *** 추가로 알아봐야 할 부분: datasets에서 가져오는 데이터 말고 다른 데이터를 가져오는 방법 *** #

In [4]:
# 한번에 훈련할 미니배치 사이즈
batch_size = 1024
# GPU시스템인지 확인
use_cuda = torch.cuda.is_available()

#dataloader 정의
train_loader = torch.utils.data.DataLoader(
                 dataset=mnist_trainset,
                 batch_size=batch_size,
                 num_workers=4,
                 pin_memory=True,
                 shuffle=True)
test_loader = torch.utils.data.DataLoader(
                dataset=mnist_testset,
                batch_size=batch_size,
                num_workers=4,
                pin_memory=True,
                shuffle=False)

In [ ]:
훈련할 neural network 정의

In [5]:
# import torch.nn as nn
# import torch.nn.functional as F

class MyNet(nn.Module):
    def __init__(self):
        super(LeNet, self).__init__()
        self.conv1 = nn.Conv2d(1, 20, 5, 1)
        self.conv2 = nn.Conv2d(20, 50, 5, 1)
        self.fc1 = nn.Linear(4*4*50, 500)
        self.fc2 = nn.Linear(500, 10)

    def forward(self, x):
        x = F.relu(self.conv1(x))
        x = F.max_pool2d(x, 2, 2)
        x = F.relu(self.conv2(x))
        x = F.max_pool2d(x, 2, 2)
        x = x.view(-1, 4*4*50)
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x
    
    def name(self):
        return "My first CNN with pyTorch!"

In [22]:
model = MyNet()

model = model.cuda()

optimizer = optim.Adam(model.parameters())

criterion = nn.CrossEntropyLoss()

In [23]:
start = time.time()
for epoch in range(10):  # loop over the dataset multiple times
    
    print(epoch)

    running_loss = 0.0
    for batch_idx, (data, target) in enumerate(train_loader):
        # get the inputs; data is a list of [inputs, labels]
        data, target = data.cuda(), target.cuda()
        
        data, target = Variable(data), Variable(target)

        # zero the parameter gradients
        optimizer.zero_grad()

        # forward + backward + optimize
        output = model.forward(data)
        loss = criterion(output, target)
        loss.backward()
        optimizer.step()

        # print statistics
        running_loss += loss.item()

    print(f'epoch {epoch}, loss: {running_loss}')
    running_loss = 0.0

print('Finished Training')
compute_t = time.time() - start
print(f'소요 시간 : {compute_t}')

0
epoch 0, loss: 39.192721858620644
1
epoch 1, loss: 7.963860556483269
2
epoch 2, loss: 4.854638423770666
3
epoch 3, loss: 3.6931767985224724
4
epoch 4, loss: 3.0206321086734533
5
epoch 5, loss: 2.4738875962793827
6
epoch 6, loss: 2.0958620626479387
7
epoch 7, loss: 1.7452487237751484
8
epoch 8, loss: 1.564565814100206
9
epoch 9, loss: 1.324633021838963
Finished Training
소요 시간 : 54.881710052490234


In [24]:
total = 0
correct = 0

for testdata in test_loader:
    data, target = testdata
    data, target = data.cuda(), target.cuda()
    output = model.forward(data)
    _, pred = torch.max(output.data, 1)
    total += target.size(0)
    correct += (pred == target).sum()
    
print("model test accuracy")
acc = correct.item() / total
print(acc)

model test accuracy
0.9907


In [31]:
model = MyNet()

optimizer = optim.SGD(model.parameters(), lr=0.01, momentum=0.9)

criterion = nn.CrossEntropyLoss()

In [32]:
start = time.time()
for epoch in range(10):  # loop over the dataset multiple times
    
    print(epoch)

    running_loss = 0.0
    for batch_idx, (data, target) in enumerate(train_loader):
        # get the inputs; data is a list of [inputs, labels]
        data, target = Variable(data), Variable(target)

        # zero the parameter gradients
        optimizer.zero_grad()

        # forward + backward + optimize
        output = model.forward(data)
        loss = criterion(output, target)
        loss.backward()
        optimizer.step()

        # print statistics
        running_loss += loss.item()
    print(f'epoch {epoch}, loss: {running_loss}')
    running_loss = 0.0

print('Finished Training')
compute_t = time.time() - start
print(f'소요 시간 : {compute_t}')

0
epoch 0, loss: 13.802269220352173
1
epoch 1, loss: 13.764296531677246
2
epoch 2, loss: 13.705218315124512
3
epoch 3, loss: 13.629156589508057
4
epoch 4, loss: 13.5269296169281
5
epoch 5, loss: 13.382502317428589
6
epoch 6, loss: 13.165460348129272
7
epoch 7, loss: 12.821048498153687
8
epoch 8, loss: 12.241288304328918
9
epoch 9, loss: 11.231246590614319
Finished Training
소요 시간 : 407.9290964603424
